Скачиваем библиотеку TensorFlow 2

In [6]:
import tensorflow as tf
v = tf.__version__
if v[0] == '2':
  print("Apropriate version!")
print(v)

Apropriate version!
2.7.0


Теперь создам константный тензор 1x1 с значением 7   

*rank 0 tesor, it has no dimentions*

In [9]:
con = tf.constant(7)
print(con)

tf.Tensor(7, shape=(), dtype=int32)


Покажу его характеристики

In [10]:
n = con.ndim
print("The number of dimentions is " + str(n))

The number of dimentions is 0


Создам константный вектор

In [12]:
vector = tf.constant([2, 4])
print(vector)
print("The number of dimentions is " + str(vector.ndim))

tf.Tensor([2 4], shape=(2,), dtype=int32)
The number of dimentions is 1


Создам матрицу


In [14]:
matrix = tf.constant([[2, 4], [5, 8]])
print(matrix)
print("The number of dimentions is " + str(matrix.ndim))

tf.Tensor(
[[2 4]
 [5 8]], shape=(2, 2), dtype=int32)
The number of dimentions is 2


Создам тензор

In [20]:
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)
print("The number of dimentions (the rank) is " + str(tensor.ndim))

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
The number of dimentions (the rank) is 3


Теперь создаем реальный тензор


In [24]:
# 1. stands for float digit
tensor_var = tf.Variable([1., 2.])
tensor_con = tf.constant([1., 2.])
print(tensor_var)
print(tensor_con)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [25]:
tensor_var[0].assign(7)
print(tensor_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([7., 2.], dtype=float32)>


In [26]:
tensor_var.assign([9, 8])
print(tensor_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([9., 8.], dtype=float32)>


# ***Random***

In [31]:
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))     # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))     # create tensor from a normal distribution 
print(random_1)
print(random_2)
random_1 == random_2    # Are they equal?

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [32]:
random_3 = tf.random.Generator.from_seed(56)  # Change the seed
random_3 = random_3.normal(shape=(3,2))
print(random_3)
random_1 == random_3

tf.Tensor(
[[-0.67958915  0.44723678]
 [-0.17811584  0.24882518]
 [ 0.49689844  0.8259971 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

Шафл

In [36]:
non_shuffle = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
print(non_shuffle)
shuffle = tf.random.shuffle(non_shuffle)
print(shuffle)

# Set the global random seed
tf.random.set_seed(42)
# Set the operation random seed
shuffle_seed = tf.random.shuffle(non_shuffle, seed=42)
print(shuffle_seed)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[7 8]
 [1 2]
 [3 4]
 [5 6]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[3 4]
 [5 6]
 [1 2]
 [7 8]], shape=(4, 2), dtype=int32)


Делаем тензоры другими методами

In [5]:
t_one = tf.ones([2,3])
t_zero = tf.zeros([4,2])
print(t_one)
print(t_zero)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)


Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

A - tensor/matrix

a - vector

In [11]:
import numpy as np
n_array = np.arange(1,13)
A = tf.constant(n_array)
B = tf.constant(n_array, shape = [2,6])
print(n_array)
print(A)
print(B)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int64)
tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int64)


* **Shape:** The length (number of elements) of each of the dimensions of a tensor.
* **Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis** or **Dimension:** A particular dimension of a tensor.
* **Size:** The total number of items in the tensor.

In [14]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
print(rank_4_tensor)
print("Shape, rank, size:")
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
Shape, rank, size:


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [59]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 2, 1, 1)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 1
Total number of elements (2*3*4*5): 4


In [17]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :3]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [18]:
# Get the last item in second matrix in first block of matrixes
# I got the last column in second matrix of first block of matrixes
print(rank_4_tensor[1, 2, :, -1])

tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)


In [19]:
# Create a rank 2 tensor (2 dimensions)
# ... means use all previous dimensions
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
print(rank_2_tensor[..., -1])

tf.Tensor([7 4], shape=(2,), dtype=int32)


There are possibilities to add more dimentions to tensors

In [24]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_4_tensor = tf.expand_dims(rank_3_tensor, axis=-1) # "-1" means last axis
print(rank_3_tensor)
print(rank_4_tensor)

tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[[10]]

  [[ 7]]]


 [[[ 3]]

  [[ 4]]]], shape=(2, 2, 1, 1), dtype=int32)


# **Tensor Operations**

---



In [27]:
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor + 10)

# Multiplication (known as element-wise multiplication)
print(tensor * 10)

# Use the tensorflow function equivalent of the '*' (multiply) operator (speed)
print(tf.multiply(tensor, 10))

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


In [121]:
# Get the sqare of each value
tf.square(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [122]:
# Get the square root of each value
tf.sqrt(tf.cast(tensor, dtype=tf.float16))

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.162, 2.646],
       [1.732, 2.   ]], dtype=float16)>

In [129]:
# Get the natural log of each value
tf.math.log(tf.cast(tensor, dtype=tf.float16))

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2.303, 1.946],
       [1.099, 1.387]], dtype=float16)>

### Matrix multiplication

In [35]:
# Matrix multiplication in TensorFlow
# use '@' or 'tf.matmul()'
print(tensor)
print(tf.matmul(tensor, tensor))

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


**Reshape != Transpose**

In [31]:
A = tf.constant([[1,2,3],[4,5,6]])

B = tf.transpose(A)

print(A)
print(B)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [30]:
C = tf.reshape(A, shape=[3,2])
print(C)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [34]:
# You can achieve the same result with parameters
v = tf.matmul(a=A, b=A, transpose_a=False, transpose_b=True)
print(v)
print(A@B)

tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


### The dot product

In [44]:
v1 = tf.tensordot(A, B, axes = 1)
v2 = tf.tensordot(A, B, axes = 2)
print(v1)
print(v2)

tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)
tf.Tensor(86, shape=(), dtype=int32)


***Axis=0*** -- Each value of matrix A multiplies to all matrix B which results in the output matrix C, which have count of matrixes shaped as B equal to size of matrix A

***Axis=1*** -- Matrix multiplication. Row * each columns, then summs and makes first value. Then changle the row and repeat

***Axis=2*** -- Matrix A overlaps matrix B. All corresponding values are multiplied and summed to one single value

In [65]:
A = tf.constant([1,2,3,4], shape=[2,2])
B = tf.constant([2,3,4,5], shape=[2,2])

print(A@B)
print(tf.matmul(A,B))
print(tf.tensordot(A,B, axes=1))

[[10 13]
 [22 29]]
tf.Tensor(
[[10 13]
 [22 29]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 13]
 [22 29]], shape=(2, 2), dtype=int32)


In [66]:
print(tf.tensordot(A,B, axes=2))
print(tf.tensordot(A,B, axes=0).numpy()) # Convert to numpy array

tf.Tensor(40, shape=(), dtype=int32)
[[[[ 2  3]
   [ 4  5]]

  [[ 4  6]
   [ 8 10]]]


 [[[ 6  9]
   [12 15]]

  [[ 8 12]
   [16 20]]]]


**Data Type**

In [67]:
A = tf.constant([1,2,3,4])
B = tf.constant([1.,2.,3.,4.])

print(A)
print(B)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [68]:
C = tf.cast(B, dtype=tf.float16)

print(C)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


**Experiments**

typically, each of these is under the *math* module, e.g. *tf.math.reduce_min()* but you can use the alias *tf.reduce_min()*

In [92]:
A = tf.constant(np.random.randint(low=-20, high=20, size=50), dtype=tf.float32)

print(A)
print(tf.abs(A))
print(tf.reduce_max(A))
print(tf.reduce_min(A))
print(tf.reduce_mean(A))
print(tf.math.reduce_std(A))              # Can't be used withput 'math' module
print(tf.math.reduce_variance(A).numpy()) # Convert to numpy form
print(tf.reduce_sum(A).numpy())

tf.Tensor(
[ 16.   1. -11.  -7.  -5.   8. -15.  13.  -1.   8.  17.  15. -16.  -1.
 -17. -12. -10. -13. -18.  10. -17. -18. -20.  -4.  18.  -9.   5.   1.
 -12.   6.  17. -14. -11. -15.   4. -13.  -6.  12. -17. -13.  13. -10.
  -7.   0.  17.  16. -12.  19.   6. -14.], shape=(50,), dtype=float32)
tf.Tensor(
[16.  1. 11.  7.  5.  8. 15. 13.  1.  8. 17. 15. 16.  1. 17. 12. 10. 13.
 18. 10. 17. 18. 20.  4. 18.  9.  5.  1. 12.  6. 17. 14. 11. 15.  4. 13.
  6. 12. 17. 13. 13. 10.  7.  0. 17. 16. 12. 19.  6. 14.], shape=(50,), dtype=float32)
tf.Tensor(19.0, shape=(), dtype=float32)
tf.Tensor(-20.0, shape=(), dtype=float32)
tf.Tensor(-2.32, shape=(), dtype=float32)
tf.Tensor(12.244901, shape=(), dtype=float32)
149.93759
-116.0


**Finding indexes**

In [97]:
A = tf.constant(np.arange(1,11), dtype=tf.int16)
B = tf.random.shuffle(A)

print(A.numpy())
print(B.numpy())

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6  8  7 10  2  5  9  4  3]


In [100]:
print("Position of a max value is: " + str(tf.argmax(B).numpy()))
print("Position of a min value is: " + str(tf.argmin(B)))

Position of a max value is: 4
Position of a min value is: tf.Tensor(0, shape=(), dtype=int64)


In [105]:
F = tf.constant(np.random.random(50))
print(F)
print("\n")

# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

tf.Tensor(
[0.40068793 0.64432723 0.48625103 0.37479642 0.17033272 0.37079715
 0.7890078  0.36862458 0.89609797 0.38673413 0.11742788 0.27423607
 0.16625645 0.28585678 0.72906144 0.45277521 0.41040757 0.9959936
 0.8234369  0.4390409  0.9979635  0.88828299 0.19426293 0.28092226
 0.32956339 0.25655581 0.49317766 0.70516938 0.82309072 0.94373178
 0.1181804  0.24305178 0.01079347 0.88018465 0.67102192 0.29452635
 0.83897789 0.39025835 0.91177984 0.53929019 0.25851325 0.98347987
 0.85518064 0.53084374 0.75777748 0.91173429 0.45950128 0.69821152
 0.99139071 0.41991346], shape=(50,), dtype=float64)


The maximum value of F is at position: 20
The maximum value of F is: 0.9979635013583527
Using tf.argmax() to index F, the maximum value of F is: 0.9979635013583527
Are the two max values the same (they should be)? True


### Squeezing a tensor (removing all single dimensions)

---



In [106]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [107]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### One-hot encoding

In [118]:
number = 7  # You choose 8th nimber of ten
tf.one_hot(number, depth = 10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)>

In [116]:
# Create a list of indices
some_list = [0, 1, 1, 2, 3, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)>

# **Manipulation variable tensors**

---



In [136]:
# Create variable tensor
A = tf.Variable(tf.ones(6), name="NamedTensor")
print(A)

<tf.Variable 'NamedTensor:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>


In [137]:
# Assign new values (shape have to be the same)
A.assign([1,1,2,3,5,8])
print(A)

<tf.Variable 'NamedTensor:0' shape=(6,) dtype=float32, numpy=array([1., 1., 2., 3., 5., 8.], dtype=float32)>


In [138]:
# Make operations
B = tf.constant(np.arange(6), dtype=tf.float32)
print(B)

A.assign_add(B)
print(A)

tf.Tensor([0. 1. 2. 3. 4. 5.], shape=(6,), dtype=float32)
<tf.Variable 'NamedTensor:0' shape=(6,) dtype=float32, numpy=array([ 1.,  2.,  4.,  6.,  9., 13.], dtype=float32)>


**Decorators** wrap a function, modifying its behavior

You can decorate your functions with ***@tf.function*** to seed it up

It turns a Python function into a callable **TensorFlow graph**

In [145]:
@tf.function
def fun1(A_m, B_m):
  return (2*A_m + B_m)

A = tf.Variable(np.arange(1,11), dtype=tf.float16)
B = tf.Variable(np.random.rand(10), dtype=tf.float16)

print(A.numpy())
print(np.array(B))
print(fun1(A,B).numpy())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.9478 0.9004 0.1349 0.7314 0.864  0.725  0.731  0.1814 0.3184 0.9854]
[ 2.947  4.9    6.137  8.734 10.87  12.73  14.734 16.19  18.31  20.98 ]


# **GPU access**

---



If the output is empty - you don't have any

In [3]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


If you've got access to a GPU, the cell above should output something like:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

You can also find information about your GPU using `!nvidia-smi`.

In [4]:
!nvidia-smi

Thu Dec 23 23:45:38 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 🛠 Exercises

4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [8]:
import numpy as np

In [17]:
A = tf.Variable(np.random.rand(5, 300), dtype=tf.float16)
B = tf.Variable(np.random.rand(5, 300), dtype=tf.float16)

print(A[2,:5])
print(B[2,:5])

tf.Tensor([0.2218   0.014084 0.1189   0.693    0.963   ], shape=(5,), dtype=float16)
tf.Tensor([0.428   0.2937  0.204   0.01095 0.525  ], shape=(5,), dtype=float16)


In [27]:
B = tf.Variable(np.random.rand(1, 224, 224, 3))

print(B[0,0,:5,1])
print("Shape of tensor: ", B.shape)
print("Size of tensor: ", tf.size(B))

C = tf.squeeze(B)
print("Shape of tensor:", C.shape)
print("Size of tensor:", tf.size(C))

tf.Tensor([0.70789798 0.61374184 0.18173433 0.15402499 0.74977521], shape=(5,), dtype=float64)
Shape of tensor:  (1, 224, 224, 3)
Size of tensor:  tf.Tensor(150528, shape=(), dtype=int32)
Shape of tensor: (224, 224, 3)
Size of tensor: tf.Tensor(150528, shape=(), dtype=int32)


In [33]:
A = tf.Variable(np.random.randint(0, 8, 10))
B = tf.one_hot(A, depth=8)

print(A)
print(B)

<tf.Variable 'Variable:0' shape=(10,) dtype=int64, numpy=array([0, 5, 0, 3, 1, 5, 7, 4, 1, 5])>
tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]], shape=(10, 8), dtype=float32)
